image: node:latest

cache:
  paths:
    - node_modules/

before_script:
  - npm install --progress=false

stages:
  - Build
  - Lint

builder:
  stage: Build
  script:
    - CI=false npm run build

linter:
  stage: Lint
  script:
    - npm run build
