image: node:latest

cache:
  paths:
    - node_modules/

before_script:
  - apt-get update -qq && apt-get install -y -qq sshpass
  - npm install --progress=false

stages:
  - Build
  - Deploy
  - Lint

builder:
  stage: Build
  script:
    - CI=false npm run build
  artifacts:
    paths:
    - build

deploy staging:
  stage: Deploy
  environment: Staging
  only:
    - master
  script:
    - export SSHPASS=$USER_PASS
    - sshpass -e scp -o stricthostkeychecking=no -r build gitlab@git.bsnk.me:/srv/ractf

linter:
  stage: Lint
  script:
    - npm run build
